function Params = get_analysis_ins

%CAP Analysis Instruction Block

Params = struct('cal_pic','1', ...
	'abr_pic','2-11', ...
	'start_resp','2', ...
	'window_resp','5', ...
	'start_back','auto', ...
	'window_back','5', ...
	'scale','4', ...
	'dir','tab-2015_05_28-ABR');
