%CAP Analysis Instruction Block

Stimuli = struct('cal_pic',1, ...
	'del_pic',-4, ...
	'abr_pic','86-90', ...
	'start_resp','auto', ...
	'window_resp','auto', ...
	'start_back','auto', ...
	'window_back','auto', ...
	'scale','auto', ...
	'automatic',1, ...
	'mode','threshold', ...
	'dir','aml-2007_02_21-CAP');
