%CAP Analysis Instruction Block

Stimuli = struct('cal_pic',1, ...
	'del_pic','11', ...
	'abr_pic','3-10', ...
	'start_resp','auto', ...
	'window_resp', 5.00, ...
	'start_back','auto', ...
	'window_back', 5.00, ...
	'scale',10.00, ...
	'automatic','no', ...
	'mode','threshold', ...
	'dir','bjm_hh-2005_07_15-CAP');
