function Params = get_analysis_ins

%CAP Analysis Instruction Block

Params = struct('cal_pic','1', ...
	'abr_pic','6-9', ...
	'start_resp','1.5', ...
	'window_resp','12', ...
	'start_back','auto', ...
	'window_back','auto', ...
	'scale','auto', ...
	'dir','pacc-2009_02_11-ABR-81t');
