function Params = get_analysis_ins

%CAP Analysis Instruction Block

Params = struct('cal_pic','1', ...
	'abr_pic','2-9', ...
	'start_resp','auto', ...
	'window_resp','auto', ...
	'start_back','auto', ...
	'window_back','auto', ...
	'scale','auto', ...
    'dir','hbc_err_beta-2007_02_20');
