%EXPLIST builds structure for file manager

general = struct('User','tab', ...
	'CurDataDir','tab-2016_04_14-CAP', ...
	'fnum',  0, ...
	'speaker','Fostex', ...
	'Volts', 1.90);

NelData = struct('General',general);