%CAP Analysis Results

function x = CAP_analysis_p4

x = struct('Stimuli',{struct('cal_pic','1 '...
,'abr_pic','4 '...
,'start_resp','2 '...
,'window_resp','5 '...
,'start_back','auto'...
,'window_back','5 '...
,'scale','4 '...
,'dir','tab-2015_05_28-ABR '...
)} ...
,'ABRmag', {[...
% StmLev CAPmag BACmag TwoSDs MasLev MasDel
[  83.39   8.79   0.76   0.76   0.00   0.00];
]});
